# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birthday', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
