# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expert', models.CharField(max_length=27, verbose_name='Keahlian')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('kode_identitas', models.CharField(default='Kosong', max_length=20, primary_key=True, serialize=False, verbose_name='Kode Identitas')),
                ('firstName', models.CharField(max_length=225, verbose_name='Nama Depan')),
                ('lastName', models.CharField(max_length=225, verbose_name='Nama Belakang')),
                ('imageUrl', models.URLField(verbose_name='Foto')),
                ('email', models.EmailField(default='Kosong', max_length=254, verbose_name='Email')),
                ('profileUrl', models.URLField(default='Kosong', verbose_name='Profile LinkedIn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_profile.User'),
        ),
    ]
