# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 22, 35, 37, 347138, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('kode_identitas', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Kode Identitas')),
                ('nama', models.CharField(max_length=200, verbose_name='Nama')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 22, 35, 37, 344631, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 22, 35, 37, 345133, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2017, 12, 8, 22, 35, 37, 346136, tzinfo=utc))),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_status.Pengguna')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='update_status.Status'),
        ),
    ]
