# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mycomment',
            old_name='updated_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='mystatus',
            old_name='updated_at',
            new_name='created_date',
        ),
    ]
