# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0002_auto_20171208_1936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='myStatus',
            new_name='Status',
        ),
    ]
