# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0002_auto_20171211_0912'),
        ('update_status', '0003_auto_20171211_2230'),
    ]

    operations = [
    ]
