# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0006_merge_20171212_1526'),
        ('update_status', '0005_merge_20171212_1541'),
    ]

    operations = [
    ]
