# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0007_auto_20171212_1613'),
        ('update_status', '0005_auto_20171212_1655'),
    ]

    operations = [
    ]
