# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0008_merge_20171212_1753'),
        ('update_status', '0009_auto_20171212_1755'),
    ]

    operations = [
    ]
