# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0011_auto_20171212_1933'),
        ('update_status', '0012_auto_20171212_2129'),
    ]

    operations = [
    ]
