# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0014_merge_20171212_2256'),
        ('update_status', '0014_merge_20171212_2305'),
    ]

    operations = [
    ]
