# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0013_merge_20171212_2237'),
        ('update_status', '0018_auto_20171213_0027'),
    ]

    operations = [
    ]
