# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0019_merge_20171213_0205'),
        ('update_status', '0019_auto_20171213_0147'),
    ]

    operations = [
    ]
