# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0020_auto_20171213_0135'),
        ('update_status', '0022_auto_20171213_0307'),
    ]

    operations = [
    ]
