# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0007_merge_20171212_1547'),
        ('update_status', '0025_auto_20171213_0501'),
    ]

    operations = [
    ]
