# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update_status', '0026_merge_20171213_0614'),
        ('update_status', '0027_auto_20171213_0700'),
    ]

    operations = [
    ]
