# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=400)),
                ('npm', models.CharField(max_length=250)),
                ('angkatan', models.CharField(max_length=400)),
                ('keahlian', models.CharField(max_length=400)),
            ],
        ),
    ]
